language: python
python:
  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - inv prep
  - inv test
  - inv bd
